### ISSUE TITLE
Accept MSA connections on port 587

### ISSUE THREAD

**Issue by crawshaw** [spilled-ink/spilld#4]
Many clients want to send email on port 587 instead of 465. For compatibility, let's support it.

The difference with 465 is that the initial connection is not made with TLS, then the client issues STARTTLS. (We will require STARTTLS.)

This requires a small change to the configuration. Probably easiest is if we add another msaAddr parameter. That's a lot of parameters. It may be time for a config struct.

**Comment by dgnorton** [comment]
@crawshaw is this the issue preventing the Geary client from connecting?
